### ISSUE TITLE
More options would be great

### ISSUE THREAD

**Issue by rodnem** [proteanstudio/sketch-palette-cleanser#23]
Options to choose the associated infos
→ I would like to only have the number of uses and not the hexa value.

Order of colors
→ Is it possible to rearrange swatches to match the color spectrum order

**Comment by abdulmhamid** [comment]
Thanks for opening this issue. We will take a look and consider these options.

**Comment by abdulmhamid** [comment]
Some initial thoughts:
- For the order of color, we populate the list in order of their use in the document. While we may add support for ROYGBIV sequencing on initial palette, we likely would not on color change due to the resource intense nature of building layers.
- For the other option, can you say more why you prefer not to have the hexa value?
